# Mod Properties
mod.group=com.cursee
mod.id=unlocked_typing
mod.name=Unlocked Typing
mod.version=1.22.0
mod.description=Unlock your typing potential in Minecraft!
mod.authors=Cursee
mod.license=MIT
mod.sources_url=https://github.com/Cursee/Unlocked-Typing
mod.homepage_url=https://curseforge.com/minecraft/mc-mods/unlocked-typing
mod.issues_url=https://github.com/Cursee/Unlocked-Typing/issues
mod.discord_url=
mod.contributors=
mod.channel_tag=

# Publishing
publish.modrinth=
publish.curseforge=

# Build Properties
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false
